CREATE TABLE IF NOT EXISTS metrics (
    id BIGINT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    name VARCHAR(32),
    type VARCHAR(32),
    counter BIGINT DEFAULT NULL,
    gauge DOUBLE PRECISION DEFAULT NULL,
    UNIQUE (name, type)
);
