CREATE TABLE IF NOT EXISTS metrics (
    id INT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    name VARCHAR(32),
    type VARCHAR(32),
    counter INTEGER DEFAULT NULL,
    gauge DOUBLE PRECISION DEFAULT NULL,
    UNIQUE (name, type)
);


